name: Changeset Check

on:
  pull_request:
    branches:
      - develop

jobs:
  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Check for changesets
        run: |
          # Check if we're on a branch that diverges from develop
          if git merge-base --is-ancestor HEAD origin/develop 2>/dev/null; then
            echo "Branch is based on develop, running changeset status..."
            pnpm changeset status
          else
            echo "Branch is not based on develop, checking for changesets manually..."
            if [ -d ".changeset" ] && [ "$(ls -A .changeset/*.md 2>/dev/null | wc -l)" -gt 0 ]; then
              echo "✅ Changesets found"
              exit 0
            else
              echo "❌ No changesets found"
              exit 1
            fi
          fi
