name: Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Check for release commit
        run: |
          if ! echo "${{ github.event.head_commit.message }}" | grep -q 'chore(release):'; then
            echo '❌ The last commit is not a release commit (chore(release):). Please run pnpx changeset version and push before triggering the release.'
            exit 1
          fi
      - name: Publish with changesets
        run: pnpx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
